Repository duozone-1-finalproject/Backend, pull requests merged in 2025-09, with the labels that each got.

#73 fix : 올데이터 콜 지분증권 오류 해결
  src/main/java/com/example/finalproject/apitest/controller/TestController.java
  src/main/java/com/example/finalproject/apitest/service/impl/TestServiceImpl.java
Labels: wontfix

#81 merge/feat/add-biz-edit
  src/main/java/com/example/finalproject/ai_backend/controller/AiReportController.java
  src/main/java/com/example/finalproject/ai_backend/controller/DebugController.java
  src/main/java/com/example/finalproject/ai_backend/controller/KafkaTestController.java
  src/main/java/com/example/finalproject/ai_backend/controller/MonitoringController.java
  src/main/java/com/example/finalproject/ai_backend/controller/VariableMappingController.java
  src/main/java/com/example/finalproject/ai_backend/dto/AiRequestDto.java
  src/main/java/com/example/finalproject/ai_backend/dto/FrontendVariableResponseDto.java
  src/main/java/com/example/finalproject/ai_backend/dto/VariableMappingRequestDto.java
  src/main/java/com/example/finalproject/ai_backend/dto/VariableMappingResponseDto.java
  src/main/java/com/example/finalproject/ai_backend/entity/IndustryTable.java
  src/main/java/com/example/finalproject/ai_backend/repository/IndustryTableRepository.java
  src/main/java/com/example/finalproject/ai_backend/service/CompanyDataMappingService.java
  src/main/java/com/example/finalproject/ai_backend/service/MainVariableMappingService.java
  src/main/java/com/example/finalproject/ai_backend/service/ReportGenerationService.java
  src/main/java/com/example/finalproject/ai_backend/service/VariableMappingService.java
  src/main/java/com/example/finalproject/dart/controller/DartController.java
  src/main/java/com/example/finalproject/dart/dto/dart/BusinessReportDto.java
  src/main/java/com/example/finalproject/dart/exception/BusinessReportException.java
  src/main/java/com/example/finalproject/dart/service/DartApiService.java
  src/main/java/com/example/finalproject/dart/service/OtherNoticeService.java
  src/main/java/com/example/finalproject/dart/service/impl/DartApiServiceImpl.java
  src/main/java/com/example/finalproject/dart/service/impl/OtherNoticeServiceImpl.java
  src/main/java/com/example/finalproject/dart_viewer/service/impl/UserVersionServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/templates/other_notice_ko.txt
Labels: documentation

#88 Merge/dev all
  src/main/java/com/example/finalproject/ai_backend/common/Constants.java
Labels: bug
