Repository duozone-1-finalproject/Backend, pull requests merged in 2025-08, with the labels that each got.

#9 Create auto_assign.yml
  .github/auto_assign.yml
Labels: good first issue

#28 깃이그노어, yml파일 수정 + 로그인 리팩토링(주형)
  .gitignore
  build.gradle
  src/main/java/com/example/finalproject/login_auth/config/SecurityConfig.java
  src/main/java/com/example/finalproject/login_auth/constant/SecurityConstants.java
  src/main/java/com/example/finalproject/login_auth/controller/AuthController.java
  src/main/java/com/example/finalproject/login_auth/controller/UserController.java
  src/main/java/com/example/finalproject/login_auth/dto/LoginRequestDto.java
  src/main/java/com/example/finalproject/login_auth/dto/LoginResponseDto.java
  src/main/java/com/example/finalproject/login_auth/dto/UserInfo.java
  src/main/java/com/example/finalproject/login_auth/entity/User.java
  src/main/java/com/example/finalproject/login_auth/handler/LocalLoginSuccessHandler.java
  src/main/java/com/example/finalproject/login_auth/handler/OAuthHandler.java
  src/main/java/com/example/finalproject/login_auth/repository/UserRepository.java
  src/main/java/com/example/finalproject/login_auth/security/JwtAuthenticationFilter.java
  src/main/java/com/example/finalproject/login_auth/security/JwtTokenProvider.java
  src/main/java/com/example/finalproject/login_auth/service/UserService.java
  src/main/java/com/example/finalproject/login_auth/util/CookieUtils.java
  src/main/java/com/example/finalproject/login_auth/util/OAuth2Utils.java
  src/main/java/com/example/finalproject/login_auth/util/PasswordValidator.java
  src/main/java/com/example/finalproject/login_auth/util/TokenUtils.java
  src/main/resources/application.yml
Labels: enhancement

#29 오픈서치 연결 v1
  build.gradle
Labels: documentation

#42 Chore : 리팩토링 후처리 완료 #41
  src/main/java/com/example/finalproject/Test02Application.java
  src/main/java/com/example/finalproject/apitest/config/DartApiProperties.java
  src/main/java/com/example/finalproject/apitest/config/DartConfig.java
  src/main/java/com/example/finalproject/apitest/config/WebConfig.java
  src/main/java/com/example/finalproject/apitest/controller/DartApiController.java
  src/main/java/com/example/finalproject/apitest/controller/DartWebController.java
  src/main/java/com/example/finalproject/apitest/controller/ReportController.java
  src/main/java/com/example/finalproject/apitest/dto/Company.java
  src/main/java/com/example/finalproject/apitest/dto/CompanyDataResponse.java
  src/main/java/com/example/finalproject/apitest/dto/CompanyOverviewResponse.java
  src/main/java/com/example/finalproject/apitest/dto/DartApiResponseDto.java
  src/main/java/com/example/finalproject/apitest/dto/DartCompanyResponse.java
  src/main/java/com/example/finalproject/apitest/dto/DartFundUsageDto.java
  src/main/java/com/example/finalproject/apitest/dto/DartGeneralInfoDto.java
  src/main/java/com/example/finalproject/apitest/dto/DartGroupDataDto.java
  src/main/java/com/example/finalproject/apitest/dto/DartRedemptionRightsDto.java
  src/main/java/com/example/finalproject/apitest/dto/DartSecuritiesInfoDto.java
  src/main/java/com/example/finalproject/apitest/dto/DartSellerInfoDto.java
  src/main/java/com/example/finalproject/apitest/dto/DartUnderwriterInfoDto.java
  src/main/java/com/example/finalproject/apitest/dto/Headquarters.java
  src/main/java/com/example/finalproject/apitest/entity/DartFundUsage.java
  src/main/java/com/example/finalproject/apitest/entity/DartGeneralInfo.java
  src/main/java/com/example/finalproject/apitest/entity/DartRedemptionRights.java
  src/main/java/com/example/finalproject/apitest/entity/DartSecuritiesInfo.java
  src/main/java/com/example/finalproject/apitest/entity/DartSellerInfo.java
  src/main/java/com/example/finalproject/apitest/entity/DartUnderwriterInfo.java
  src/main/java/com/example/finalproject/apitest/repository/DartFundUsageRepository.java
  src/main/java/com/example/finalproject/apitest/repository/DartGeneralInfoRepository.java
  src/main/java/com/example/finalproject/apitest/repository/DartRedemptionRightsRepository.java
  src/main/java/com/example/finalproject/apitest/repository/DartSecuritiesInfoRepository.java
  src/main/java/com/example/finalproject/apitest/repository/DartSellerInfoRepository.java
  src/main/java/com/example/finalproject/apitest/repository/DartUnderwriterInfoRepository.java
  src/main/java/com/example/finalproject/apitest/service/DartApiServiceImpl2.java
  src/main/java/com/example/finalproject/apitest/service/DartFetchUseCase.java
  src/main/java/com/example/finalproject/apitest/service/DartQueryUseCase.java
  src/main/java/com/example/finalproject/apitest/service/DartService2.java
  src/main/resources/application.yml
Labels: enhancement
